"""empty message

Revision ID: 1b3402dcfc15
Revises: 5c32ff33ddf3
Create Date: 2023-03-15 16:51:35.740166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3402dcfc15'
down_revision = '5c32ff33ddf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Post_tags'), ['tags'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Post_tags'))

    # ### end Alembic commands ###
