"""empty message

Revision ID: 6cf865cb5bf2
Revises: 1b3402dcfc15
Create Date: 2023-03-17 18:45:08.697177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf865cb5bf2'
down_revision = '1b3402dcfc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('date_of_publication', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_Post_tags')
        batch_op.create_index(batch_op.f('ix_Post_date_of_publication'), ['date_of_publication'], unique=False)
        batch_op.create_index(batch_op.f('ix_Post_likes'), ['likes'], unique=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_User_about_me'), ['about_me'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_interests'), ['interests'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_interests'))
        batch_op.drop_index(batch_op.f('ix_User_about_me'))
        batch_op.drop_column('interests')

    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Post_likes'))
        batch_op.drop_index(batch_op.f('ix_Post_date_of_publication'))
        batch_op.create_index('ix_Post_tags', ['tags'], unique=False)
        batch_op.drop_column('likes')
        batch_op.drop_column('date_of_publication')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
