"""empty message

Revision ID: da8c88b4aa70
Revises: 6cf865cb5bf2
Create Date: 2023-03-18 09:47:14.301172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8c88b4aa70'
down_revision = '6cf865cb5bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
